### ISSUE TITLE
used-letter-tracking

### ISSUE THREAD

**Issue by Nemo11235** [Nemo11235/CS160-Final-Project#32]
We should implement the function into the first playable version which keeps track of the status of each letter that the user attempted, correct, partial, and incorrect.

**Comment by iannaduran** [comment]
Test Cases:
Description: Created a usedLetters State that keeps track of all the user's inputs and their most favorable feedback produced from it (correct is kept over partially correct, etc.). Logic is implemented in gameUtils.js, Keyboard.js, and HomePage.js files.

Steps to test:
-run react program
-type input into grid using keyboard and press enter
-inspect the react page and view the components of HomePage (this is achieved using React Developer Tools extension for google chrome)
-usedLetters (State 4) is an array containing the feedback of each letter the user has inputted
