### ISSUE TITLE
color-on-grid-keyboard

### ISSUE THREAD

**Issue by Nemo11235** [Nemo11235/CS160-Final-Project#37]
We should have color on the grid and keyboard to show hints:
Green: correct;
Yellow: partial;
grey: incorrect;

**Comment by Nemo11235** [comment]
completed on the branch attached

**Comment by makter20** [comment]
Test cases:
~It shows color on the grid and keyboard according to user input
~If the user puts the completely wrong word then letters on the keyboard will be gray and the cell on the grid will be gray. 
~Partial correct letters are yellows on the grid and keyboard 
~correct letters are green on the keyboard and grid
