### ISSUE TITLE
UI Design and placement

### ISSUE THREAD

**Issue by Nemo11235** [Nemo11235/CS160-Final-Project#4]
We need the UI for the components of the game, including the following:

1. Keyboard buttons including 26 letters, backspace, and enter;
2. Gameboard grid to fill in the letters;
3. Hamburger menu;
4. Color Palette;
5. Dark Theme;
6. Game logo;
7. Multiplayer Page;
8. Tutorial Page;
9. About Us Page;
10. Game win overlay;
11. Program animations;
12. User custom word list upload page on Profile;
13. Account/Profile Page

**Comment by terryhong4** [comment]
Link to the Adobe XD prototype:

https://xd.adobe.com/view/f54c3953-95de-4937-aa34-379cc3ba8fbf-a01f/?fullscreen
