### ISSUE TITLE
tutorial-page

### ISSUE THREAD

**Issue by Nemo11235** [Nemo11235/CS160-Final-Project#40]
Implement the tutorial page according to the [design](https://xd.adobe.com/view/f54c3953-95de-4937-aa34-379cc3ba8fbf-a01f/?fullscreen ):

**Comment by khoapham999** [comment]
Test Cases:
The tutorial page is designed based on the prototype.
The tutorial page runs correctly and displays clearly on localhost.
Users can go to tutorial page from the hamburger menu.
