### ISSUE TITLE
waiting-screen

### ISSUE THREAD

**Issue by Nemo11235** [Nemo11235/CS160-Final-Project#74]
Waiting for screen for multiplayer when there's only one player in the room. It should disappear when the second player joins.

When the second player joins, it will disappear after a count down and start the game. Before that, player won't be able to do anything.

It should show the room id for the first player to copy.

**Comment by iannaduran** [comment]
Test Cases:
-From the Hamburger Menu select multiplayer, enter a username and room ID, and click on join button
-The waiting screen will be displayed along with the room ID
-Once the second player joins the room, the second player can view the waiting screen with the timer overlaying it. The timer is displayed for both players and will begin counting down starting from 3. 
-Once 1 is reached, the Multiplayer game contents is displayed for both players to begin playing.
-If players want to play again, both players will be able to follow the previous steps on the Multiplier Join Room screen and experience the same waiting screen and countdown timer components.
